  -- Insertar Mesas
  INSERT INTO RESTAURANTE.TBL_MESA (NUMERO, ESTADO) VALUES (1, 'Libre');
  INSERT INTO RESTAURANTE.TBL_MESA (NUMERO, ESTADO) VALUES (2, 'Ocupada');
  INSERT INTO RESTAURANTE.TBL_MESA (NUMERO, ESTADO) VALUES (3, 'Por Desocupar');

  -- Insertar Empleados
  INSERT INTO RESTAURANTE.TBL_EMPLEADO (NOMBRE, TIPO, TURNO) VALUES ('Juan Pérez', 'Mesero', 'Mañana');
  INSERT INTO RESTAURANTE.TBL_EMPLEADO (NOMBRE, TIPO, TURNO) VALUES ('Ana López', 'Mesero', 'Tarde');
  INSERT INTO RESTAURANTE.TBL_EMPLEADO (NOMBRE, TIPO, TURNO) VALUES ('Carlos Ruiz', 'Cajero', 'Mañana');

  -- Insertar Caja
  INSERT INTO RESTAURANTE.TBL_CAJA (SALDO_APERTURA, SALDO_CIERRE, EMPLEADO_ID, HORA_INICIO, HORA_FIN) 
  VALUES (500.00, NULL, 3, SYSTIMESTAMP, NULL);

  -- Insertar Productos
  INSERT INTO RESTAURANTE.TBL_PRODUCTO (NOMBRE, TIPO, PRECIO) VALUES ('Coca-Cola', 'Bebida', 2.50);
  INSERT INTO RESTAURANTE.TBL_PRODUCTO (NOMBRE, TIPO, PRECIO) VALUES ('Hamburguesa', 'Comida', 5.99);
  INSERT INTO RESTAURANTE.TBL_PRODUCTO (NOMBRE, TIPO, PRECIO) VALUES ('Pastel de Chocolate', 'Postre', 3.75);

  -- Insertar Menú
  INSERT INTO RESTAURANTE.TBL_MENU (NOMBRE) VALUES ('Menú Ejecutivo');
  INSERT INTO RESTAURANTE.TBL_MENU (NOMBRE) VALUES ('Menú Infantil');

  -- Insertar Relación Menú-Producto
  INSERT INTO RESTAURANTE.TBL_MENU_PRODUCTO (MENU_ID, PRODUCTO_ID, CANTIDAD) VALUES (1, 2, 1); -- Hamburguesa en Menú Ejecutivo
  INSERT INTO RESTAURANTE.TBL_MENU_PRODUCTO (MENU_ID, PRODUCTO_ID, CANTIDAD) VALUES (1, 1, 1); -- Coca-Cola en Menú Ejecutivo
  INSERT INTO RESTAURANTE.TBL_MENU_PRODUCTO (MENU_ID, PRODUCTO_ID, CANTIDAD) VALUES (2, 2, 1); -- Hamburguesa en Menú Infantil

  -- Insertar Pedido
  INSERT INTO RESTAURANTE.TBL_PEDIDO (MESA_ID, EMPLEADO_ID, ESTADO, HORA_INICIO, HORA_FIN) 
  VALUES (1, 1, 'Pendiente', SYSTIMESTAMP, NULL);

  -- Insertar Detalle Pedido
  INSERT INTO RESTAURANTE.TBL_DETALLE_PEDIDO (PEDIDO_ID, PRODUCTO_ID, MENU_ID, CANTIDAD, PRECIO, ESTADO, HORA_SOLICITUD) 
  VALUES (1, 1, null, 1, 5.99, 'Despachado', SYSTIMESTAMP);

  -- Insertar Factura
  INSERT INTO RESTAURANTE.TBL_FACTURA (PEDIDO_ID, CAJA_ID, TOTAL, METODO_PAGO, FECHA) 
  VALUES (1, 1, 8.49, 'Efectivo', SYSTIMESTAMP);
  
  COMMIT;

