alter session set "_ORACLE_SCRIPT"=true;
CREATE USER RESTAURANTE IDENTIFIED BY restaurante123;
GRANT CONNECT, RESOURCE TO RESTAURANTE;
ALTER USER RESTAURANTE QUOTA UNLIMITED ON USERS;

CREATE TABLE RESTAURANTE.TBL_MESAS (
  ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NUMERO NUMBER NOT NULL,
  ESTADO VARCHAR2(20) CHECK (ESTADO IN ('Libre', 'Ocupada', 'Por Desocupar')) NOT NULL
);

CREATE TABLE RESTAURANTE.TBL_EMPLEADOS (
  ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NOMBRE VARCHAR2(100) NOT NULL,
  TIPO VARCHAR2(20) CHECK (TIPO IN ('Cajero', 'Mesero')) NOT NULL,
  TURNO VARCHAR2(20) NOT NULL
);

CREATE TABLE RESTAURANTE.TBL_CAJAS (
  ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  SALDO_APERTURA NUMBER(10,2) NOT NULL,
  SALDO_CIERRE NUMBER(10,2),
  EMPLEADO_ID NUMBER NOT NULL,
  HORA_INICIO TIMESTAMP NOT NULL,
  HORA_FIN TIMESTAMP,
  FOREIGN KEY (EMPLEADO_ID) REFERENCES RESTAURANTE.TBL_EMPLEADOS(ID)
);

CREATE TABLE RESTAURANTE.TBL_PEDIDOS (
  ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  MESA_ID NUMBER NOT NULL,
  EMPLEADO_ID NUMBER NOT NULL,
  ESTADO VARCHAR2(20) CHECK (ESTADO IN ('Pendiente', 'En proceso', 'Finalizado')) NOT NULL,
  HORA_INICIO TIMESTAMP NOT NULL,
  HORA_FIN TIMESTAMP,
  FOREIGN KEY (MESA_ID) REFERENCES RESTAURANTE.TBL_MESAS(ID),
  FOREIGN KEY (EMPLEADO_ID) REFERENCES RESTAURANTE.TBL_EMPLEADOS(ID)
);

CREATE TABLE RESTAURANTE.TBL_PRODUCTOS (
  ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NOMBRE VARCHAR2(100) NOT NULL,
  TIPO VARCHAR2(50) CHECK (TIPO IN ('Bebida', 'Comida', 'Postre')) NOT NULL,
  PRECIO NUMBER(10,2) NOT NULL
);

CREATE TABLE RESTAURANTE.TBL_MENUS (
  ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NOMBRE VARCHAR2(100) NOT NULL
);

CREATE TABLE RESTAURANTE.TBL_MENU_PRODUCTOS (
  ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  MENU_ID NUMBER NOT NULL,
  PRODUCTO_ID NUMBER NOT NULL,
  CANTIDAD NUMBER NOT NULL,
  FOREIGN KEY (MENU_ID) REFERENCES RESTAURANTE.TBL_MENUS(ID),
  FOREIGN KEY (PRODUCTO_ID) REFERENCES RESTAURANTE.TBL_PRODUCTOS(ID)
);

CREATE TABLE RESTAURANTE.TBL_DETALLE_PEDIDO (
  ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  PEDIDO_ID NUMBER NOT NULL,
  PRODUCTO_ID NUMBER NOT NULL,
  MENU_ID NUMBER,
  CANTIDAD NUMBER NOT NULL,
  PRECIO NUMBER(10,2) NOT NULL,
  ESTADO VARCHAR2(20) CHECK (ESTADO IN ('En preparación', 'Despachado')) NOT NULL,
  HORA_SOLICITUD TIMESTAMP NOT NULL,
  FOREIGN KEY (PEDIDO_ID) REFERENCES RESTAURANTE.TBL_PEDIDOS(ID),
  FOREIGN KEY (PRODUCTO_ID) REFERENCES RESTAURANTE.TBL_PRODUCTOS(ID),
  FOREIGN KEY (MENU_ID) REFERENCES RESTAURANTE.TBL_MENUS(ID)
);

CREATE TABLE RESTAURANTE.TBL_FACTURAS (
  ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  PEDIDO_ID NUMBER NOT NULL,
  CAJA_ID NUMBER NOT NULL,
  TOTAL NUMBER(10,2) NOT NULL,
  METODO_PAGO VARCHAR2(20) CHECK (METODO_PAGO IN ('Efectivo', 'Tarjeta')) NOT NULL,
  FECHA TIMESTAMP NOT NULL,
  FOREIGN KEY (PEDIDO_ID) REFERENCES RESTAURANTE.TBL_PEDIDOS(ID),
  FOREIGN KEY (CAJA_ID) REFERENCES RESTAURANTE.TBL_CAJAS(ID)
);

CREATE TABLE RESTAURANTE.TBL_BITACORA (
  ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  USUARIO VARCHAR2(100) NOT NULL,
  OPERACION VARCHAR2(50) NOT NULL,
  FECHA TIMESTAMP NOT NULL,
  DETALLE CLOB NOT NULL
);

CREATE USER USR_CONSULTA IDENTIFIED BY consulta_password;
GRANT CONNECT TO USR_CONSULTA;
GRANT SELECT ON RESTAURANTE.TBL_MESAS TO USR_CONSULTA;
GRANT SELECT ON RESTAURANTE.TBL_EMPLEADOS TO USR_CONSULTA;
GRANT SELECT ON RESTAURANTE.TBL_CAJAS TO USR_CONSULTA;
GRANT SELECT ON RESTAURANTE.TBL_PEDIDOS TO USR_CONSULTA;
GRANT SELECT ON RESTAURANTE.TBL_PRODUCTOS TO USR_CONSULTA;
GRANT SELECT ON RESTAURANTE.TBL_MENUS TO USR_CONSULTA;
GRANT SELECT ON RESTAURANTE.TBL_MENU_PRODUCTOS TO USR_CONSULTA;
GRANT SELECT ON RESTAURANTE.TBL_DETALLE_PEDIDO TO USR_CONSULTA;
GRANT SELECT ON RESTAURANTE.TBL_FACTURAS TO USR_CONSULTA;
GRANT SELECT ON RESTAURANTE.TBL_BITACORA TO USR_CONSULTA;

CREATE USER USR_ADMIN IDENTIFIED BY admin_password;
GRANT CONNECT, RESOURCE TO USR_ADMIN;
GRANT ALL PRIVILEGES ON RESTAURANTE.TBL_MESAS TO USR_ADMIN;
GRANT ALL PRIVILEGES ON RESTAURANTE.TBL_EMPLEADOS TO USR_ADMIN;
GRANT ALL PRIVILEGES ON RESTAURANTE.TBL_CAJAS TO USR_ADMIN;
GRANT ALL PRIVILEGES ON RESTAURANTE.TBL_PEDIDOS TO USR_ADMIN;
GRANT ALL PRIVILEGES ON RESTAURANTE.TBL_PRODUCTOS TO USR_ADMIN;
GRANT ALL PRIVILEGES ON RESTAURANTE.TBL_MENUS TO USR_ADMIN;
GRANT ALL PRIVILEGES ON RESTAURANTE.TBL_MENU_PRODUCTOS TO USR_ADMIN;
GRANT ALL PRIVILEGES ON RESTAURANTE.TBL_DETALLE_PEDIDO TO USR_ADMIN;
GRANT ALL PRIVILEGES ON RESTAURANTE.TBL_FACTURAS TO USR_ADMIN;
GRANT ALL PRIVILEGES ON RESTAURANTE.TBL_BITACORA TO USR_ADMIN;