-- Abrir una caja
CREATE OR REPLACE PROCEDURE RESTAURANTE.SP_I_APERTURA_CAJA (
  p_EMPLEADO_ID IN NUMBER,
  p_SALDO_APERTURA IN NUMBER
) AS
BEGIN
  INSERT INTO RESTAURANTE.TBL_CAJA (EMPLEADO_ID, SALDO_APERTURA, HORA_INICIO)
  VALUES (p_EMPLEADO_ID, p_SALDO_APERTURA, SYSTIMESTAMP);
  
  COMMIT;
END SP_I_APERTURA_CAJA;
/

-- Cerrar una caja
CREATE OR REPLACE PROCEDURE RESTAURANTE.SP_U_CIERRE_CAJA (
  p_ID IN NUMBER,
  p_SALDO_CIERRE IN NUMBER
) AS
BEGIN
  UPDATE RESTAURANTE.TBL_CAJA
  SET SALDO_CIERRE = p_SALDO_CIERRE, HORA_FIN = SYSTIMESTAMP
  WHERE ID = p_ID;
  
  COMMIT;
END SP_U_CIERRE_CAJA;
/


create or replace PROCEDURE SP_S_CAJA (p_cursor OUT SYS_REFCURSOR) AS
BEGIN
  OPEN p_cursor FOR SELECT * FROM RESTAURANTE.TBL_CAJA;
END SP_S_CAJA;
