-- Agregar producto o combo a un pedido
CREATE OR REPLACE PROCEDURE RESTAURANTE.SP_I_DETALLE_PEDIDO (
  p_PEDIDO_ID IN NUMBER,
  p_PRODUCTO_ID IN NUMBER,
  p_MENU_ID IN NUMBER,
  p_CANTIDAD IN NUMBER,
  p_PRECIO IN NUMBER
) AS
BEGIN
  INSERT INTO RESTAURANTE.TBL_DETALLE_PEDIDO (PEDIDO_ID, PRODUCTO_ID, MENU_ID, CANTIDAD, PRECIO, ESTADO, HORA_SOLICITUD)
  VALUES (p_PEDIDO_ID, p_PRODUCTO_ID, p_MENU_ID, p_CANTIDAD, p_PRECIO, 'En preparación', SYSTIMESTAMP);
  
  COMMIT;
END SP_I_DETALLE_PEDIDO;
/

-- Consultar pedidos en preparación
CREATE OR REPLACE PROCEDURE RESTAURANTE.SP_S_PEDIDO_COCINA (p_cursor OUT SYS_REFCURSOR) AS
BEGIN
OPEN p_cursor FOR
  SELECT D.ID, D.PEDIDO_ID, M.NUMERO AS NUMERO_MESA, P.NOMBRE AS PRODUCTO, D.CANTIDAD, D.ESTADO
  FROM RESTAURANTE.TBL_DETALLE_PEDIDO D
  JOIN RESTAURANTE.TBL_PEDIDO PE ON D.PEDIDO_ID = PE.ID
  JOIN RESTAURANTE.TBL_MESA M ON PE.MESA_ID = M.ID
  JOIN RESTAURANTE.TBL_PRODUCTO P ON D.PRODUCTO_ID = P.ID
  WHERE D.ESTADO = 'En preparación';

END SP_S_PEDIDO_COCINA;
/

-- Actualizar estado de pedido en cocina
CREATE OR REPLACE PROCEDURE RESTAURANTE.SP_U_ESTADO_PEDIDO (
  p_DETALLE_PEDIDO_ID IN NUMBER,
  p_ESTADO IN VARCHAR2
) AS
BEGIN
  UPDATE RESTAURANTE.TBL_DETALLE_PEDIDO
  SET ESTADO = p_ESTADO
  WHERE ID = p_DETALLE_PEDIDO_ID;
  
  COMMIT;
END SP_U_ESTADO_PEDIDO;
/

-- Seleccionar todos los productos
CREATE OR REPLACE PROCEDURE RESTAURANTE.SP_S_PRODUCTO (p_cursor OUT SYS_REFCURSOR) AS
BEGIN
  OPEN p_cursor FOR
    SELECT ID, NOMBRE, TIPO, PRECIO 
    FROM RESTAURANTE.TBL_PRODUCTO;
END SP_S_PRODUCTO;
/

-- Seleccionar todos los menus
CREATE OR REPLACE PROCEDURE RESTAURANTE.SP_S_MENU (p_cursor OUT SYS_REFCURSOR) AS
BEGIN
  OPEN p_cursor FOR
    SELECT ID, NOMBRE 
    FROM RESTAURANTE.TBL_MENU;
END SP_S_MENU;
/

-- Seleccionar los productos de un menu especifico
CREATE OR REPLACE PROCEDURE RESTAURANTE.SP_S_MENU_PRODUCTO (p_MENU_ID IN NUMBER, p_cursor OUT SYS_REFCURSOR) AS
BEGIN
  OPEN p_cursor FOR
    SELECT MP.ID, M.NOMBRE AS MENU, P.NOMBRE, MP.CANTIDAD
    FROM RESTAURANTE.TBL_MENU_PRODUCTO MP
    JOIN RESTAURANTE.TBL_MENU M ON MP.MENU_ID = M.ID
    JOIN RESTAURANTE.TBL_PRODUCTO P ON MP.PRODUCTO_ID = P.ID
    WHERE MP.MENU_ID = p_MENU_ID;
END SP_S_MENU_PRODUCTO;
/


