-- Generar una factura
CREATE OR REPLACE PROCEDURE RESTAURANTE.SP_I_FACTURAR (
  p_PEDIDO_ID IN NUMBER,
  p_CAJA_ID IN NUMBER,
  p_METODO_PAGO IN VARCHAR2
) AS
  v_TOTAL NUMBER(10,2);
BEGIN
  -- Calcular el total sumando el subtotal de cada ítem en el pedido
  SELECT COALESCE(SUM(CANTIDAD * PRECIO), 0)
  INTO v_TOTAL
  FROM RESTAURANTE.TBL_DETALLE_PEDIDO
  WHERE PEDIDO_ID = p_PEDIDO_ID;

  -- Insertar la factura con el total calculado
  INSERT INTO RESTAURANTE.TBL_FACTURA (PEDIDO_ID, CAJA_ID, TOTAL, METODO_PAGO, FECHA)
  VALUES (p_PEDIDO_ID, p_CAJA_ID, v_TOTAL, p_METODO_PAGO, SYSTIMESTAMP);

  -- Marcar el pedido como Finalizado
  UPDATE RESTAURANTE.TBL_PEDIDO
  SET ESTADO = 'Finalizado', HORA_FIN = SYSTIMESTAMP
  WHERE ID = p_PEDIDO_ID;

  COMMIT;
END SP_I_FACTURAR;


-- Obtener Facturas
create or replace PROCEDURE RESTAURANTE.SP_S_FACTURA (p_cursor OUT SYS_REFCURSOR) AS
BEGIN
  OPEN p_cursor FOR SELECT * FROM RESTAURANTE.TBL_FACTURA;
END SP_S_FACTURA;
/