-- Generar una factura
CREATE OR REPLACE PROCEDURE RESTAURANTE.SP_I_FACTURAR (
  p_PEDIDO_ID IN NUMBER,
  p_CAJA_ID IN NUMBER,
  p_TOTAL IN NUMBER,
  p_METODO_PAGO IN VARCHAR2
) AS
BEGIN
  INSERT INTO RESTAURANTE.TBL_FACTURA (PEDIDO_ID, CAJA_ID, TOTAL, METODO_PAGO, FECHA)
  VALUES (p_PEDIDO_ID, p_CAJA_ID, p_TOTAL, p_METODO_PAGO, SYSTIMESTAMP);
  
  COMMIT;
END SP_I_FACTURAR;
/

-- Obtener Facturas
create or replace PROCEDURE RESTAURANTE.SP_S_FACTURA (p_cursor OUT SYS_REFCURSOR) AS
BEGIN
  OPEN p_cursor FOR SELECT * FROM RESTAURANTE.TBL_FACTURA;
END SP_S_FACTURA;
