-- Asignar un mesero a una mesa
CREATE OR REPLACE PROCEDURE RESTAURANTE.SP_U_ASIGNAR_MESERO (
  p_MESA_ID IN NUMBER,
  p_EMPLEADO_ID IN NUMBER
) AS
BEGIN
  UPDATE RESTAURANTE.TBL_PEDIDO
  SET EMPLEADO_ID = p_EMPLEADO_ID
  WHERE MESA_ID = p_MESA_ID AND ESTADO = 'Pendiente';
  
  COMMIT;
END SP_U_ASIGNAR_MESERO;
/

-- Consultar mesero asignado a una mesa
CREATE OR REPLACE PROCEDURE RESTAURANTE.SP_S_MESERO_POR_MESA (
  p_MESA_ID IN NUMBER
) AS
v_mesero_id NUMBER;
BEGIN
  SELECT EMPLEADO_ID INTO v_mesero_id
  FROM RESTAURANTE.TBL_PEDIDO
  WHERE MESA_ID = p_MESA_ID AND ESTADO = 'Pendiente';

  DBMS_OUTPUT.PUT_LINE('Mesero asignado a mesa ' || p_MESA_ID || ': ' || v_mesero_id);
END SP_S_MESERO_POR_MESA;
/