-- Trigger para la tabla TBL_MESAS
CREATE OR REPLACE TRIGGER RESTAURANTE.TRG_BITACORA_TBL_MESAS_BU_BD
BEFORE UPDATE OR DELETE ON RESTAURANTE.TBL_MESAS
FOR EACH ROW
BEGIN
  IF UPDATING THEN
    INSERT INTO RESTAURANTE.TBL_BITACORA (USUARIO, OPERACION, FECHA, DETALLE)
    VALUES (USER, 'UPDATE', CURRENT_TIMESTAMP,
      'Antes: {ID:' || :OLD.ID || ', NUMERO:' || :OLD.NUMERO || ', ESTADO:"' || :OLD.ESTADO || '"} ' ||
      'Después: {ID:' || :NEW.ID || ', NUMERO:' || :NEW.NUMERO || ', ESTADO:"' || :NEW.ESTADO || '"}');
  ELSIF DELETING THEN
    INSERT INTO RESTAURANTE.TBL_BITACORA (USUARIO, OPERACION, FECHA, DETALLE)
    VALUES (USER, 'DELETE', CURRENT_TIMESTAMP,
      'Eliminado: {ID:' || :OLD.ID || ', NUMERO:' || :OLD.NUMERO || ', ESTADO:"' || :OLD.ESTADO || '"}');
  END IF;
END;
/

-- Trigger para la tabla TBL_EMPLEADOS
CREATE OR REPLACE TRIGGER RESTAURANTE.TRG_BITACORA_TBL_EMPLEADOS_BU_BD
BEFORE UPDATE OR DELETE ON RESTAURANTE.TBL_EMPLEADOS
FOR EACH ROW
BEGIN
  IF UPDATING THEN
    INSERT INTO RESTAURANTE.TBL_BITACORA (USUARIO, OPERACION, FECHA, DETALLE)
    VALUES (USER, 'UPDATE', CURRENT_TIMESTAMP,
      'Antes: {ID:' || :OLD.ID || ', NOMBRE:"' || :OLD.NOMBRE || '", TIPO:"' || :OLD.TIPO || '", TURNO:"' || :OLD.TURNO || '"} ' ||
      'Después: {ID:' || :NEW.ID || ', NOMBRE:"' || :NEW.NOMBRE || '", TIPO:"' || :NEW.TIPO || '", TURNO:"' || :NEW.TURNO || '"}');
  ELSIF DELETING THEN
    INSERT INTO RESTAURANTE.TBL_BITACORA (USUARIO, OPERACION, FECHA, DETALLE)
    VALUES (USER, 'DELETE', CURRENT_TIMESTAMP,
      'Eliminado: {ID:' || :OLD.ID || ', NOMBRE:"' || :OLD.NOMBRE || '", TIPO:"' || :OLD.TIPO || '", TURNO:"' || :OLD.TURNO || '"}');
  END IF;
END;
/

-- Trigger para la tabla TBL_CAJAS
CREATE OR REPLACE TRIGGER RESTAURANTE.TRG_BITACORA_TBL_CAJAS_BU_BD
BEFORE UPDATE OR DELETE ON RESTAURANTE.TBL_CAJAS
FOR EACH ROW
BEGIN
  IF UPDATING THEN
    INSERT INTO RESTAURANTE.TBL_BITACORA (USUARIO, OPERACION, FECHA, DETALLE)
    VALUES (USER, 'UPDATE', CURRENT_TIMESTAMP,
      'Antes: {ID:' || :OLD.ID || ', SALDO_APERTURA:' || :OLD.SALDO_APERTURA || ', SALDO_CIERRE:' || :OLD.SALDO_CIERRE || '} ' ||
      'Después: {ID:' || :NEW.ID || ', SALDO_APERTURA:' || :NEW.SALDO_APERTURA || ', SALDO_CIERRE:' || :NEW.SALDO_CIERRE || '}');
  ELSIF DELETING THEN
    INSERT INTO RESTAURANTE.TBL_BITACORA (USUARIO, OPERACION, FECHA, DETALLE)
    VALUES (USER, 'DELETE', CURRENT_TIMESTAMP,
      'Eliminado: {ID:' || :OLD.ID || ', SALDO_APERTURA:' || :OLD.SALDO_APERTURA || ', SALDO_CIERRE:' || :OLD.SALDO_CIERRE || '}');
  END IF;
END;
/

-- Trigger para la tabla TBL_PEDIDOS
CREATE OR REPLACE TRIGGER RESTAURANTE.TRG_BITACORA_TBL_PEDIDOS_BU_BD
BEFORE UPDATE OR DELETE ON RESTAURANTE.TBL_PEDIDOS
FOR EACH ROW
BEGIN
  IF UPDATING THEN
    INSERT INTO RESTAURANTE.TBL_BITACORA (USUARIO, OPERACION, FECHA, DETALLE)
    VALUES (USER, 'UPDATE', CURRENT_TIMESTAMP,
      'Antes: {ID:' || :OLD.ID || ', ESTADO:"' || :OLD.ESTADO || '", FECHA:"' || TO_CHAR(:OLD.FECHA, 'YYYY-MM-DD HH24:MI:SS') || '"} ' ||
      'Después: {ID:' || :NEW.ID || ', ESTADO:"' || :NEW.ESTADO || '", FECHA:"' || TO_CHAR(:NEW.FECHA, 'YYYY-MM-DD HH24:MI:SS') || '"}');
  ELSIF DELETING THEN
    INSERT INTO RESTAURANTE.TBL_BITACORA (USUARIO, OPERACION, FECHA, DETALLE)
    VALUES (USER, 'DELETE', CURRENT_TIMESTAMP,
      'Eliminado: {ID:' || :OLD.ID || ', ESTADO:"' || :OLD.ESTADO || '", FECHA:"' || TO_CHAR(:OLD.FECHA, 'YYYY-MM-DD HH24:MI:SS') || '"}');
  END IF;
END;
/

-- Trigger para la tabla TBL_PRODUCTOS
CREATE OR REPLACE TRIGGER RESTAURANTE.TRG_BITACORA_TBL_PRODUCTOS_BU_BD
BEFORE UPDATE OR DELETE ON RESTAURANTE.TBL_PRODUCTOS
FOR EACH ROW
BEGIN
  IF UPDATING THEN
    INSERT INTO RESTAURANTE.TBL_BITACORA (USUARIO, OPERACION, FECHA, DETALLE)
    VALUES (USER, 'UPDATE', CURRENT_TIMESTAMP,
      'Antes: {ID:' || :OLD.ID || ', NOMBRE:"' || :OLD.NOMBRE || '", PRECIO:' || :OLD.PRECIO || '} ' ||
      'Después: {ID:' || :NEW.ID || ', NOMBRE:"' || :NEW.NOMBRE || '", PRECIO:' || :NEW.PRECIO || '}');
  ELSIF DELETING THEN
    INSERT INTO RESTAURANTE.TBL_BITACORA (USUARIO, OPERACION, FECHA, DETALLE)
    VALUES (USER, 'DELETE', CURRENT_TIMESTAMP,
      'Eliminado: {ID:' || :OLD.ID || ', NOMBRE:"' || :OLD.NOMBRE || '", PRECIO:' || :OLD.PRECIO || '}');
  END IF;
END;
/

-- Trigger para la tabla TBL_FACTURAS
CREATE OR REPLACE TRIGGER RESTAURANTE.TRG_BITACORA_TBL_FACTURAS_BU_BD
BEFORE UPDATE OR DELETE ON RESTAURANTE.TBL_FACTURAS
FOR EACH ROW
BEGIN
  IF UPDATING THEN
    INSERT INTO RESTAURANTE.TBL_BITACORA (USUARIO, OPERACION, FECHA, DETALLE)
    VALUES (USER, 'UPDATE', CURRENT_TIMESTAMP,
      'Antes: {ID:' || :OLD.ID || ', TOTAL:' || :OLD.TOTAL || ', METODO_PAGO:"' || :OLD.METODO_PAGO || '"} ' ||
      'Después: {ID:' || :NEW.ID || ', TOTAL:' || :NEW.TOTAL || ', METODO_PAGO:"' || :NEW.METODO_PAGO || '"}');
  ELSIF DELETING THEN
    INSERT INTO RESTAURANTE.TBL_BITACORA (USUARIO, OPERACION, FECHA, DETALLE)
    VALUES (USER, 'DELETE', CURRENT_TIMESTAMP,
      'Eliminado: {ID:' || :OLD.ID || ', TOTAL:' || :OLD.TOTAL || ', METODO_PAGO:"' || :OLD.METODO_PAGO || '"}');
  END IF;
END;
/