-- Trigger para la tabla TBL_MESA
CREATE OR REPLACE TRIGGER RESTAURANTE.TRG_BITACORA_TBL_MESA_BU_BD
BEFORE UPDATE OR DELETE ON RESTAURANTE.TBL_MESA
FOR EACH ROW
BEGIN
  IF UPDATING THEN
    INSERT INTO RESTAURANTE.TBL_BITACORA (USUARIO, OPERACION, FECHA, DETALLE)
    VALUES (USER, 'UPDATE', CURRENT_TIMESTAMP,
      'Antes: {ID:' || :OLD.ID || ', NUMERO:' || :OLD.NUMERO || ', ESTADO:"' || :OLD.ESTADO || '"} ' ||
      'Después: {ID:' || :NEW.ID || ', NUMERO:' || :NEW.NUMERO || ', ESTADO:"' || :NEW.ESTADO || '"}');
  ELSIF DELETING THEN
    INSERT INTO RESTAURANTE.TBL_BITACORA (USUARIO, OPERACION, FECHA, DETALLE)
    VALUES (USER, 'DELETE', CURRENT_TIMESTAMP,
      'Eliminado: {ID:' || :OLD.ID || ', NUMERO:' || :OLD.NUMERO || ', ESTADO:"' || :OLD.ESTADO || '"}');
  END IF;
END;
/

-- Trigger para la tabla TBL_EMPLEADO
CREATE OR REPLACE TRIGGER RESTAURANTE.TRG_BITACORA_TBL_EMPLEADO_BU_BD
BEFORE UPDATE OR DELETE ON RESTAURANTE.TBL_EMPLEADO
FOR EACH ROW
BEGIN
  IF UPDATING THEN
    INSERT INTO RESTAURANTE.TBL_BITACORA (USUARIO, OPERACION, FECHA, DETALLE)
    VALUES (USER, 'UPDATE', CURRENT_TIMESTAMP,
      'Antes: {ID:' || :OLD.ID || ', NOMBRE:"' || :OLD.NOMBRE || '", TIPO:"' || :OLD.TIPO || '", TURNO:"' || :OLD.TURNO || '"} ' ||
      'Después: {ID:' || :NEW.ID || ', NOMBRE:"' || :NEW.NOMBRE || '", TIPO:"' || :NEW.TIPO || '", TURNO:"' || :NEW.TURNO || '"}');
  ELSIF DELETING THEN
    INSERT INTO RESTAURANTE.TBL_BITACORA (USUARIO, OPERACION, FECHA, DETALLE)
    VALUES (USER, 'DELETE', CURRENT_TIMESTAMP,
      'Eliminado: {ID:' || :OLD.ID || ', NOMBRE:"' || :OLD.NOMBRE || '", TIPO:"' || :OLD.TIPO || '", TURNO:"' || :OLD.TURNO || '"}');
  END IF;
END;
/

-- Trigger para la tabla TBL_CAJA
CREATE OR REPLACE TRIGGER RESTAURANTE.TRG_BITACORA_TBL_CAJA_BU_BD
BEFORE UPDATE OR DELETE ON RESTAURANTE.TBL_CAJA
FOR EACH ROW
BEGIN
  IF UPDATING THEN
    INSERT INTO RESTAURANTE.TBL_BITACORA (USUARIO, OPERACION, FECHA, DETALLE)
    VALUES (USER, 'UPDATE', CURRENT_TIMESTAMP,
      'Antes: {ID:' || :OLD.ID || ', SALDO_APERTURA:' || :OLD.SALDO_APERTURA || ', SALDO_CIERRE:' || :OLD.SALDO_CIERRE || '} ' ||
      'Después: {ID:' || :NEW.ID || ', SALDO_APERTURA:' || :NEW.SALDO_APERTURA || ', SALDO_CIERRE:' || :NEW.SALDO_CIERRE || '}');
  ELSIF DELETING THEN
    INSERT INTO RESTAURANTE.TBL_BITACORA (USUARIO, OPERACION, FECHA, DETALLE)
    VALUES (USER, 'DELETE', CURRENT_TIMESTAMP,
      'Eliminado: {ID:' || :OLD.ID || ', SALDO_APERTURA:' || :OLD.SALDO_APERTURA || ', SALDO_CIERRE:' || :OLD.SALDO_CIERRE || '}');
  END IF;
END;
/

-- Trigger para la tabla TBL_PEDIDO
CREATE OR REPLACE TRIGGER RESTAURANTE.TRG_BITACORA_TBL_PEDIDO_BU_BD
BEFORE UPDATE OR DELETE ON RESTAURANTE.TBL_PEDIDO
FOR EACH ROW
BEGIN
  IF UPDATING THEN
    INSERT INTO RESTAURANTE.TBL_BITACORA (USUARIO, OPERACION, FECHA, DETALLE)
    VALUES (USER, 'UPDATE', CURRENT_TIMESTAMP,
      'Antes: { ' || CHR(10) ||
      '  "ID": ' || :OLD.ID || ',' || CHR(10) ||
      '  "MESA_ID": ' || :OLD.MESA_ID || ',' || CHR(10) ||
      '  "EMPLEADO_ID": ' || :OLD.EMPLEADO_ID || ',' || CHR(10) ||
      '  "ESTADO": "' || :OLD.ESTADO || '",' || CHR(10) ||
      '  "HORA_INICIO": "' || TO_CHAR(:OLD.HORA_INICIO, 'YYYY-MM-DD HH24:MI:SS') || '",' || CHR(10) ||
      '  "HORA_FIN": "' || NVL(TO_CHAR(:OLD.HORA_FIN, 'YYYY-MM-DD HH24:MI:SS'), 'NULL') || '"' || CHR(10) ||
      '} ' || CHR(10) ||
      'Después: { ' || CHR(10) ||
      '  "ID": ' || :NEW.ID || ',' || CHR(10) ||
      '  "MESA_ID": ' || :NEW.MESA_ID || ',' || CHR(10) ||
      '  "EMPLEADO_ID": ' || :NEW.EMPLEADO_ID || ',' || CHR(10) ||
      '  "ESTADO": "' || :NEW.ESTADO || '",' || CHR(10) ||
      '  "HORA_INICIO": "' || TO_CHAR(:NEW.HORA_INICIO, 'YYYY-MM-DD HH24:MI:SS') || '",' || CHR(10) ||
      '  "HORA_FIN": "' || NVL(TO_CHAR(:NEW.HORA_FIN, 'YYYY-MM-DD HH24:MI:SS'), 'NULL') || '"' || CHR(10) ||
      '}'
    );
  ELSIF DELETING THEN
    INSERT INTO RESTAURANTE.TBL_BITACORA (USUARIO, OPERACION, FECHA, DETALLE)
    VALUES (USER, 'DELETE', CURRENT_TIMESTAMP,
      'Eliminado: { ' || CHR(10) ||
      '  "ID": ' || :OLD.ID || ',' || CHR(10) ||
      '  "MESA_ID": ' || :OLD.MESA_ID || ',' || CHR(10) ||
      '  "EMPLEADO_ID": ' || :OLD.EMPLEADO_ID || ',' || CHR(10) ||
      '  "ESTADO": "' || :OLD.ESTADO || '",' || CHR(10) ||
      '  "HORA_INICIO": "' || TO_CHAR(:OLD.HORA_INICIO, 'YYYY-MM-DD HH24:MI:SS') || '",' || CHR(10) ||
      '  "HORA_FIN": "' || NVL(TO_CHAR(:OLD.HORA_FIN, 'YYYY-MM-DD HH24:MI:SS'), 'NULL') || '"' || CHR(10) ||
      '}'
    );
  END IF;
END;
/

-- Trigger para la tabla TBL_PRODUCTO
CREATE OR REPLACE TRIGGER RESTAURANTE.TRG_BITACORA_TBL_PRODUCTO_BU_BD
BEFORE UPDATE OR DELETE ON RESTAURANTE.TBL_PRODUCTO
FOR EACH ROW
BEGIN
  IF UPDATING THEN
    INSERT INTO RESTAURANTE.TBL_BITACORA (USUARIO, OPERACION, FECHA, DETALLE)
    VALUES (USER, 'UPDATE', CURRENT_TIMESTAMP,
      'Antes: {ID:' || :OLD.ID || ', NOMBRE:"' || :OLD.NOMBRE || '", PRECIO:' || :OLD.PRECIO || '} ' ||
      'Después: {ID:' || :NEW.ID || ', NOMBRE:"' || :NEW.NOMBRE || '", PRECIO:' || :NEW.PRECIO || '}');
  ELSIF DELETING THEN
    INSERT INTO RESTAURANTE.TBL_BITACORA (USUARIO, OPERACION, FECHA, DETALLE)
    VALUES (USER, 'DELETE', CURRENT_TIMESTAMP,
      'Eliminado: {ID:' || :OLD.ID || ', NOMBRE:"' || :OLD.NOMBRE || '", PRECIO:' || :OLD.PRECIO || '}');
  END IF;
END;
/

-- Trigger para la tabla TBL_FACTURA
CREATE OR REPLACE TRIGGER RESTAURANTE.TRG_BITACORA_TBL_FACTURA_BU_BD
BEFORE UPDATE OR DELETE ON RESTAURANTE.TBL_FACTURA
FOR EACH ROW
BEGIN
  IF UPDATING THEN
    INSERT INTO RESTAURANTE.TBL_BITACORA (USUARIO, OPERACION, FECHA, DETALLE)
    VALUES (USER, 'UPDATE', CURRENT_TIMESTAMP,
      'Antes: {ID:' || :OLD.ID || ', TOTAL:' || :OLD.TOTAL || ', METODO_PAGO:"' || :OLD.METODO_PAGO || '"} ' ||
      'Después: {ID:' || :NEW.ID || ', TOTAL:' || :NEW.TOTAL || ', METODO_PAGO:"' || :NEW.METODO_PAGO || '"}');
  ELSIF DELETING THEN
    INSERT INTO RESTAURANTE.TBL_BITACORA (USUARIO, OPERACION, FECHA, DETALLE)
    VALUES (USER, 'DELETE', CURRENT_TIMESTAMP,
      'Eliminado: {ID:' || :OLD.ID || ', TOTAL:' || :OLD.TOTAL || ', METODO_PAGO:"' || :OLD.METODO_PAGO || '"}');
  END IF;
END;
/