GRANT CREATE VIEW TO RESTAURANTE;

CREATE OR REPLACE VIEW RESTAURANTE.VW_VENTAS_DIARIAS AS
SELECT 
  TRUNC(F.FECHA) AS FECHA,
  F.METODO_PAGO,
  SUM(F.TOTAL) AS TOTAL_DIA
FROM 
  RESTAURANTE.TBL_FACTURA F
GROUP BY 
  TRUNC(F.FECHA), F.METODO_PAGO;
  /

  CREATE OR REPLACE VIEW RESTAURANTE.VW_PEDIDOS_POR_MESERO AS
SELECT 
  E.ID AS EMPLEADO_ID,
  E.NOMBRE,
  COUNT(P.ID) AS TOTAL_PEDIDOS,
  SUM(F.TOTAL) AS TOTAL_FACTURADO
FROM 
  RESTAURANTE.TBL_EMPLEADO E
  LEFT JOIN RESTAURANTE.TBL_PEDIDO P ON E.ID = P.EMPLEADO_ID
  LEFT JOIN RESTAURANTE.TBL_FACTURA F ON F.PEDIDO_ID = P.ID
WHERE 
  E.TIPO = 'Mesero'
GROUP BY 
  E.ID, E.NOMBRE;
/

CREATE OR REPLACE VIEW RESTAURANTE.VW_PEDIDOS_EN_CURSO AS
SELECT 
  P.ID AS PEDIDO_ID,
  M.NUMERO AS MESA,
  E.NOMBRE AS MESERO,
  P.ESTADO,
  P.HORA_INICIO,
  LISTAGG(DP.ESTADO, ', ') WITHIN GROUP (ORDER BY DP.ID) AS ESTADOS_DETALLES
FROM 
  RESTAURANTE.TBL_PEDIDO P
  JOIN RESTAURANTE.TBL_MESA M ON P.MESA_ID = M.ID
  JOIN RESTAURANTE.TBL_EMPLEADO E ON P.EMPLEADO_ID = E.ID
  LEFT JOIN RESTAURANTE.TBL_DETALLE_PEDIDO DP ON P.ID = DP.PEDIDO_ID
WHERE 
  P.ESTADO <> 'Finalizado'
GROUP BY 
  P.ID, M.NUMERO, E.NOMBRE, P.ESTADO, P.HORA_INICIO;
/

CREATE OR REPLACE VIEW RESTAURANTE.VW_PRODUCTOS_MAS_VENDIDOS AS
SELECT 
  P.NOMBRE,
  P.TIPO,
  SUM(DP.CANTIDAD) AS TOTAL_VENDIDO,
  SUM(DP.CANTIDAD * DP.PRECIO) AS TOTAL_INGRESOS
FROM 
  RESTAURANTE.TBL_DETALLE_PEDIDO DP
  JOIN RESTAURANTE.TBL_PRODUCTO P ON DP.PRODUCTO_ID = P.ID
GROUP BY 
  P.NOMBRE, P.TIPO
ORDER BY 
  TOTAL_VENDIDO DESC;
/

CREATE OR REPLACE VIEW RESTAURANTE.VW_CIERRES_CAJA AS
SELECT 
  C.ID AS CAJA_ID,
  E.NOMBRE AS EMPLEADO,
  E.TURNO,
  C.HORA_INICIO,
  C.HORA_FIN,
  C.SALDO_APERTURA,
  C.SALDO_CIERRE,
  (C.SALDO_CIERRE - C.SALDO_APERTURA) AS DIFERENCIA
FROM 
  RESTAURANTE.TBL_CAJA C
  JOIN RESTAURANTE.TBL_EMPLEADO E ON C.EMPLEADO_ID = E.ID
WHERE 
  C.HORA_FIN IS NOT NULL
ORDER BY 
  C.HORA_FIN DESC;
/

CREATE OR REPLACE VIEW RESTAURANTE.VW_ESTADISTICAS_VENTAS AS
SELECT 
  TRUNC(F.FECHA, 'IW') AS SEMANA,
  TRUNC(F.FECHA, 'MM') AS MES,
  TRUNC(F.FECHA, 'YYYY') AS ANIO,
  SUM(F.TOTAL) AS TOTAL_VENTAS
FROM 
  RESTAURANTE.TBL_FACTURA F
GROUP BY 
  TRUNC(F.FECHA, 'IW'), TRUNC(F.FECHA, 'MM'), TRUNC(F.FECHA, 'YYYY');
/

CREATE OR REPLACE VIEW RESTAURANTE.VW_TOP_PRODUCTOS_SEMANALES AS
SELECT 
  P.NOMBRE,
  P.TIPO,
  SUM(D.CANTIDAD) AS TOTAL_VENDIDO,
  SUM(D.CANTIDAD * D.PRECIO) AS TOTAL_INGRESOS,
  TRUNC(D.HORA_SOLICITUD, 'IW') AS SEMANA
FROM 
  RESTAURANTE.TBL_DETALLE_PEDIDO D
  JOIN RESTAURANTE.TBL_PRODUCTO P ON D.PRODUCTO_ID = P.ID
WHERE 
  D.HORA_SOLICITUD >= TRUNC(SYSDATE, 'IW') -- semana actual
GROUP BY 
  P.NOMBRE, P.TIPO, TRUNC(D.HORA_SOLICITUD, 'IW')
ORDER BY 
  TOTAL_VENDIDO DESC;
/

CREATE OR REPLACE VIEW RESTAURANTE.VW_TOP_PRODUCTOS_MENSUALES AS
SELECT 
  P.NOMBRE,
  P.TIPO,
  SUM(D.CANTIDAD) AS TOTAL_VENDIDO,
  SUM(D.CANTIDAD * D.PRECIO) AS TOTAL_INGRESOS,
  TRUNC(D.HORA_SOLICITUD, 'MM') AS MES
FROM 
  RESTAURANTE.TBL_DETALLE_PEDIDO D
  JOIN RESTAURANTE.TBL_PRODUCTO P ON D.PRODUCTO_ID = P.ID
WHERE 
  D.HORA_SOLICITUD >= TRUNC(SYSDATE, 'MM') -- mes actual
GROUP BY 
  P.NOMBRE, P.TIPO, TRUNC(D.HORA_SOLICITUD, 'MM')
ORDER BY 
  TOTAL_VENDIDO DESC;
/

CREATE OR REPLACE VIEW RESTAURANTE.VW_TOP_PRODUCTOS_ANUALES AS
SELECT 
  P.NOMBRE,
  P.TIPO,
  SUM(D.CANTIDAD) AS TOTAL_VENDIDO,
  SUM(D.CANTIDAD * D.PRECIO) AS TOTAL_INGRESOS,
  TRUNC(D.HORA_SOLICITUD, 'YYYY') AS ANIO
FROM 
  RESTAURANTE.TBL_DETALLE_PEDIDO D
  JOIN RESTAURANTE.TBL_PRODUCTO P ON D.PRODUCTO_ID = P.ID
WHERE 
  D.HORA_SOLICITUD >= TRUNC(SYSDATE, 'YYYY') -- año actual
GROUP BY 
  P.NOMBRE, P.TIPO, TRUNC(D.HORA_SOLICITUD, 'YYYY')
ORDER BY 
  TOTAL_VENDIDO DESC;
/